export default {
  SET_MENU: 'SET_MENU',
  SET_LOADING: 'SET_LOADING',
  SET_HOUSE_LIST: 'SET_HOUSE_LIST',
  SET_LEASE_DETAIL: 'SET_LEASE_DETAIL',
  SET_BUILDING_INFO: 'SET_BUILDING_INFO',
  SET_USER_INFO: 'SET_USER_INFO',
  SET_SEARCH_PARAMS: 'SET_SEARCH_PARAMS',
  SET_FIRST_LOAD: 'SET_FIRST_LOAD',
};
